Develop
Raypr5/MercadoCzOnline pull request #9
Opened 2022-04-12 20:55 UTC by jeliel10

2022-04-13 23:07 UTC, ejrgeek requested changes

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/CompraController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/ComercianteController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/ProdutoController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/TipoBoletoController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/TipoCartaoController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/controller/TipoPixController.java
> +    @GetMapping("/buscar")
"todos"

2022-04-13 23:07 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/ProjetoMC/service/ComercianteService.java
> +    public Comerciante saveOrUpdate(Comerciante comerciante){
ingles ou portugues

2022-04-14 02:18 UTC, jeliel10 commented
Correções foram feitas nos métodos de cada classe service, trocando todos eles para o português. Do mesmo modo com as requisições do Postman, todas elas estão em português agora.

2022-05-10 19:20 UTC, closed without merging